const request = require('supertest')
const app = require('../src/app')
const File = require('../src/models/file')
const { userOne, setupDatabase } = require('./fixtures/db')
const { emptyDirectory } = require('../src/routers/utils/s3')
